--Numero de quejas por producto y subproducto, dividido por trimestre para el año 2023
SELECT 
  PRODUCT,
  SUBPRODUCT,
  SUM(CASE WHEN MONTH(DATERECEIVED) BETWEEN 1 AND 3 THEN 1 ELSE 0 END) AS Q1,
  SUM(CASE WHEN MONTH(DATERECEIVED) BETWEEN 4 AND 6 THEN 1 ELSE 0 END) AS Q2,
  SUM(CASE WHEN MONTH(DATERECEIVED) BETWEEN 7 AND 9 THEN 1 ELSE 0 END) AS Q3,
  SUM(CASE WHEN MONTH(DATERECEIVED) BETWEEN 10 AND 12 THEN 1 ELSE 0 END) AS Q4
FROM 
  complaints_df5
WHERE 
  YEAR(DATERECEIVED) = 2023
GROUP BY 
  PRODUCT,
  SUBPRODUCT
ORDER BY 
  PRODUCT ASC,
  SUBPRODUCT ASC;